// Generated by CoffeeScript 1.9.2
var bodyParser;

bodyParser = require("body-parser");

module.exports = function(app, express) {
  app.set('port', process.env.PORT || 8080);
  return app.use(bodyParser.json({}));
};
