// Generated by CoffeeScript 1.9.2
var AUTH_TOKEN, url;

url = require('url');

AUTH_TOKEN = 'fdsjfk32r90r32orjf3902j3j3felkfds';

module.exports = function(app) {
  var auth;
  auth = function(req, res, next) {
    var query, url_parts;
    console.log('AUTHENTICATING');
    url_parts = url.parse(req.url, true);
    query = url_parts.query;
    if (query['secret'] !== AUTH_TOKEN) {
      return res.json(401, null);
    }
    console.log('PASSED AUTH');
    return next();
  };
  app.get('/api/v1', function(req, res) {
    return res.json(200);
  });
  app.post('api/v1/user/login', function(req, res) {
    var user;
    user = req.body;
    console.log("user is " + JSON.stringify(user));
    return res.json(200);
  });
  app.post('/api/v1/user/socialLogin', function(req, res) {
    var user;
    user = req.body;
    console.log("user is " + JSON.stringify(user));
    return res.json(200);
  });
  return app.use(function(req, res, next) {
    return res.json(404, null);
  });
};
